import type { Metadata } from "next";
import Navbar from "../components/navbar";
import "./globals.css";
import { Providers } from "./providers";
import { Footer } from "@/components/Footer";
import { RecaptchaProviderWrapper } from "@/components/RecaptchaProviderWrapper"; 
import {NextIntlClientProvider} from 'next-intl';

export const metadata: Metadata = {
  title: "Djordje Milutin | Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "app/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <NextIntlClientProvider>
          <RecaptchaProviderWrapper>
            <Providers>
              <Navbar />
              {/* <div className="ab"></div> */}
              <main className="min-h-screen flex">{children}</main>
              <Footer />
            </Providers>
          </RecaptchaProviderWrapper>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
