import type { Metadata } from "next";
import Navbar from "../components/navbar";
import "./globals.css";
import { Providers } from "./providers";
import { Footer } from "@/components/Footer";
import { RecaptchaProviderWrapper } from "@/components/RecaptchaProviderWrapper"; 

export const metadata: Metadata = {
  title: "Djordje Milutin | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <RecaptchaProviderWrapper>
          <Providers>
            <Navbar />
            {/* <div className="ab"></div> */}
            <main className="min-h-screen flex">{children}</main>
            <Footer />
          </Providers>
        </RecaptchaProviderWrapper>
      </body>
    </html>
  );
}
