import type { Metadata } from "next";
import Navbar from "../components/navbar";
import "./globals.css";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Djordje Milutin | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-background">
        <Providers>
          <Navbar />

          <main className=" mx-25 my-10 px-6 py-7 ">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
